title: "Bořek Běhavý Wildlife Photography"
author: "Bořek Běhavý"
description: "Explore the beauty of wildlife through the lens of Bořek Běhavý." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "borek.behavy.fotograf@gmail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
facebook_username: borekwildlifephoto
#flickr_username: username
instagram_username: borek_wildlifephoto
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

minima:
  skin: auto

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
